/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.Usuario

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idAlumno 
 * @param usuario 
 * @param numeroTarjeta 
 * @param dniFrente 
 * @param dniDorso 
 * @param cuentaCorriente 
 */


data class Alumno (

    @SerializedName("idAlumno")
    val idAlumno: kotlin.Long? = null,

    @SerializedName("usuario")
    val usuario: Usuario? = null,

    @SerializedName("numeroTarjeta")
    val numeroTarjeta: kotlin.String? = null,

    @SerializedName("dniFrente")
    val dniFrente: kotlin.String? = null,

    @SerializedName("dniDorso")
    val dniDorso: kotlin.String? = null,

    @SerializedName("cuentaCorriente")
    val cuentaCorriente: kotlin.String? = null

) {


}

