/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param numeroTarjeta 
 * @param dniFrente 
 * @param dniDorso 
 * @param cuentaCorriente 
 */


data class AlumnoActualizarDTO (

    @SerializedName("numeroTarjeta")
    val numeroTarjeta: kotlin.String? = null,

    @SerializedName("dniFrente")
    val dniFrente: kotlin.String? = null,

    @SerializedName("dniDorso")
    val dniDorso: kotlin.String? = null,

    @SerializedName("tipoTarjeta")
    val tipoTarjeta: kotlin.String? = null,

    @SerializedName("vencimiento")
    val vencimiento: kotlin.String? = null,

    @SerializedName("codigoSeguridad")
    val codigoSeguridad: kotlin.String? = null,

    @SerializedName("numeroTramite")
    val numeroTramite: kotlin.String? = null

)

