/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param accessToken 
 * @param userId 
 * @param role 
 * @param email 
 */


data class AuthenticationResponse (

    @SerializedName("access_token")
    val accessToken: kotlin.String? = null,

    @SerializedName("user_id")
    val userId: kotlin.Long? = null,

    @SerializedName("role")
    val role: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null

) {


}

