/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param alias 
 * @param password 
 */


data class AuthenticationRequest (

    @SerializedName("alias")
    val alias: kotlin.String? = null,

    @SerializedName("password")
    val password: kotlin.String? = null

) {


}

