/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.Usuario

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idCalificacion 
 * @param usuario 
 * @param receta 
 * @param calificacion 
 * @param comentarios 
 */


data class Calificacion (

    @SerializedName("idCalificacion")
    val idCalificacion: kotlin.Long? = null,

    @SerializedName("usuario")
    val usuario: Usuario? = null,

    @SerializedName("receta")
    val receta: kotlin.Any? = null,

    @SerializedName("calificacion")
    val calificacion: kotlin.Int? = null,

    @SerializedName("comentarios")
    val comentarios: kotlin.String? = null

) {


}

