/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idReceta 
 * @param calificacion 
 */


data class CalificacionRequest (

    @SerializedName("idReceta")
    val idReceta: kotlin.Long? = null,

    @SerializedName("calificacion")
    val calificacion: kotlin.Int? = null

) {


}

