/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idReceta 
 * @param comentario 
 */


data class ComentarioRequest (

    @SerializedName("idReceta")
    val idReceta: kotlin.Long? = null,

    @SerializedName("texto")
    val texto: kotlin.String? = null

) {


}

