/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombreUsuario 
 * @param texto 
 */


data class ComentarioResponse (

    @SerializedName("nombreUsuario")
    val nombreUsuario: kotlin.String? = null,

    @SerializedName("texto")
    val texto: kotlin.String? = null

) {


}

