/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipo 
 * @param extension 
 * @param url 
 */


data class Contenido (

    @SerializedName("tipo")
    val tipo: kotlin.String? = null,

    @SerializedName("extension")
    val extension: kotlin.String? = null,

    @SerializedName("url")
    val url: kotlin.String? = null

) {


}

