/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idCronograma 
 * @param nombreSede 
 * @param direccionSede 
 * @param descripcionCurso 
 * @param duracion 
 * @param precio 
 * @param fechaInicio 
 * @param fechaFin 
 * @param vacantesDisponibles 
 */


data class CursoDisponibleDTO (

    @SerializedName("idCronograma")
    val idCronograma: kotlin.Long? = null,

    @SerializedName("nombreSede")
    val nombreSede: kotlin.String? = null,

    @SerializedName("direccionSede")
    val direccionSede: kotlin.String? = null,

    @SerializedName("descripcionCurso")
    val descripcionCurso: kotlin.String? = null,

    @SerializedName("duracion")
    val duracion: kotlin.String? = null,

    @SerializedName("precio")
    val precio: kotlin.Double? = null,

    @SerializedName("fechaInicio")
    val fechaInicio: java.time.OffsetDateTime? = null,

    @SerializedName("fechaFin")
    val fechaFin: java.time.OffsetDateTime? = null,

    @SerializedName("vacantesDisponibles")
    val vacantesDisponibles: kotlin.Int? = null

) {


}

