/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idFoto 
 * @param urlFoto 
 * @param extension 
 * @param descripcion 
 * @param receta 
 */


data class Foto (

    @SerializedName("idFoto")
    val idFoto: kotlin.Long? = null,

    @SerializedName("urlFoto")
    val urlFoto: kotlin.String? = null,

    @SerializedName("extension")
    val extension: kotlin.String? = null,

    @SerializedName("descripcion")
    val descripcion: kotlin.String? = null,

    @SerializedName("receta")
    val receta: kotlin.Any? = null

) {


}

