/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idIngrediente 
 * @param nombreIngrediente 
 * @param cantidad 
 * @param unidadDescripcion 
 * @param observaciones 
 */


data class IngredienteCantidadDTO (

    @SerializedName("idIngrediente")
    val idIngrediente: kotlin.Long? = null,

    @SerializedName("nombreIngrediente")
    val nombreIngrediente: kotlin.String? = null,

    @SerializedName("cantidad")
    val cantidad: kotlin.Double? = null,

    @SerializedName("unidadDescripcion")
    val unidadDescripcion: kotlin.String? = null,

    @SerializedName("observaciones")
    val observaciones: kotlin.String? = null

) {


}

