/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombreIngrediente 
 * @param cantidad 
 * @param unidad 
 * @param observaciones 
 */


data class IngredienteCantidad (

    @SerializedName("nombreIngrediente")
    val nombreIngrediente: kotlin.String? = null,

    @SerializedName("cantidad")
    val cantidad: kotlin.Double? = null,

    @SerializedName("unidad")
    val unidad: kotlin.String? = null,

    @SerializedName("observaciones")
    val observaciones: kotlin.String? = null

) {


}

