/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idIngrediente 
 * @param nombre 
 */


data class Ingrediente (

    @SerializedName("idIngrediente")
    val idIngrediente: kotlin.Long? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null

) {


}

