/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.Pasos

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idContenido 
 * @param paso 
 * @param tipoContenido 
 * @param extension 
 * @param urlContenido 
 */


data class Multimedia (

    @SerializedName("idContenido")
    val idContenido: kotlin.Long? = null,

    @SerializedName("paso")
    val paso: Pasos? = null,

    @SerializedName("tipoContenido")
    val tipoContenido: kotlin.String? = null,

    @SerializedName("extension")
    val extension: kotlin.String? = null,

    @SerializedName("urlContenido")
    val urlContenido: kotlin.String? = null

) {


}

