/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tipoContenido 
 * @param extension 
 * @param urlContenido 
 */


data class MultimediaCrear (

    @SerializedName("tipoContenido")
    val tipoContenido: kotlin.String? = null,

    @SerializedName("extension")
    val extension: kotlin.String? = null,

    @SerializedName("urlContenido")
    val urlContenido: kotlin.String? = null

) {


}

