/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.FotoCrear
import com.example.saborchef.models.IngredienteCantidad
import com.example.saborchef.models.PasoCrear

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idUsuario 
 * @param nombreReceta 
 * @param descripcionReceta 
 * @param fotoPrincipal 
 * @param cantidadPersonas 
 * @param tipo 
 * @param ingredientes 
 * @param pasos 
 * @param fotos 
 */


data class RecetaCrearRequest (

    @SerializedName("idUsuario")
    val idUsuario: kotlin.Long? = null,

    @SerializedName("nombreReceta")
    val nombreReceta: kotlin.String? = null,

    @SerializedName("descripcionReceta")
    val descripcionReceta: kotlin.String? = null,

    @SerializedName("duracion")
    val duracion: kotlin.Int? = null,

    @SerializedName("fotoPrincipal")
    val fotoPrincipal: kotlin.String? = null,

    @SerializedName("porciones")
    val porciones: kotlin.Int? = null,

    @SerializedName("tipo")
    val tipo: kotlin.String? = null,

    @SerializedName("ingredientes")
    val ingredientes: kotlin.collections.List<IngredienteCantidad>? = null,

    @SerializedName("pasos")
    val pasos: kotlin.collections.List<PasoCrear>? = null,

    @SerializedName("fotos")
    val fotos: kotlin.collections.List<FotoCrear>? = null

) {


}

