/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombre 
 * @param usuario 
 * @param tipo 
 * @param ingredientesIncluidos 
 * @param ingredientesExcluidos 
 * @param orden 
 */


data class RecetaFiltroRequest (

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("usuario")
    val usuario: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("tipo")
    val tipo: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("ingredientesIncluidos")
    val ingredientesIncluidos: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("ingredientesExcluidos")
    val ingredientesExcluidos: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("orden")
    val orden: kotlin.String? = null

) {


}

