/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.ComentarioResponse
import com.example.saborchef.models.IngredienteDetalle
import com.example.saborchef.models.PasoDetalle

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idReceta 
 * @param nombre 
 * @param descripcion 
 * @param fotoPrincipal 
 * @param porciones 
 * @param tipo 
 * @param nombreUsuario 
 * @param ingredientes 
 * @param pasos 
 * @param fotos 
 * @param comentarios 
 * @param promedioCalificacion 
 * @param duracion 
 */


data class RecetaDetalleResponse (

    @SerializedName("idReceta")
    val idReceta: kotlin.Long? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("descripcion")
    val descripcion: kotlin.String? = null,

    @SerializedName("fotoPrincipal")
    val fotoPrincipal: kotlin.String? = null,

    @SerializedName("porciones")
    val porciones: kotlin.Int? = null,

    @SerializedName("tipo")
    val tipo: kotlin.String? = null,

    @SerializedName("nombreUsuario")
    val nombreUsuario: kotlin.String? = null,

    @SerializedName("ingredientes")
    val ingredientes: kotlin.collections.List<IngredienteDetalle>? = null,

    @SerializedName("pasos")
    val pasos: kotlin.collections.List<PasoDetalle>? = null,

    @SerializedName("fotos")
    val fotos: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("comentarios")
    val comentarios: kotlin.collections.List<ComentarioResponse>? = null,

    @SerializedName("promedioCalificacion")
    val promedioCalificacion: kotlin.Double? = null,

    @SerializedName("duracion")
    val duracion: kotlin.Int? = null

) {


}

