/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.IngredienteCantidadDTO

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idRecetaOriginal 
 * @param nombreReceta 
 * @param nombreUsuario 
 * @param tipoReceta 
 * @param descripcionReceta 
 * @param porcionesOriginal 
 * @param porcionesEscaladas 
 * @param factorEscalado 
 * @param ingredientes 
 */


data class RecetaEscaladaResponse (

    @SerializedName("idRecetaOriginal")
    val idRecetaOriginal: kotlin.Long? = null,

    @SerializedName("nombreReceta")
    val nombreReceta: kotlin.String? = null,

    @SerializedName("nombreUsuario")
    val nombreUsuario: kotlin.String? = null,

    @SerializedName("tipoReceta")
    val tipoReceta: kotlin.String? = null,

    @SerializedName("descripcionReceta")
    val descripcionReceta: kotlin.String? = null,

    @SerializedName("porcionesOriginal")
    val porcionesOriginal: kotlin.Int? = null,

    @SerializedName("porcionesEscaladas")
    val porcionesEscaladas: kotlin.Int? = null,

    @SerializedName("factorEscalado")
    val factorEscalado: kotlin.Double? = null,

    @SerializedName("ingredientes")
    val ingredientes: kotlin.collections.List<IngredienteCantidadDTO>? = null

) {


}

