/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.Calificacion
import com.example.saborchef.models.Foto
import com.example.saborchef.models.Pasos
import com.example.saborchef.models.TipoReceta
import com.example.saborchef.models.Usuario
import com.example.saborchef.models.Utilizado

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idReceta 
 * @param usuario 
 * @param nombreReceta 
 * @param descripcionReceta 
 * @param fotoPrincipal 
 * @param porciones 
 * @param duracion 
 * @param cantidadPersonas 
 * @param tipo 
 * @param pasos 
 * @param utilizados 
 * @param fotos 
 * @param calificaciones 
 * @param fechaCreacion 
 * @param habilitada 
 */


data class Receta (

    @SerializedName("idReceta")
    val idReceta: kotlin.Long? = null,

    @SerializedName("usuario")
    val usuario: Usuario? = null,

    @SerializedName("nombreReceta")
    val nombreReceta: kotlin.String? = null,

    @SerializedName("descripcionReceta")
    val descripcionReceta: kotlin.String? = null,

    @SerializedName("fotoPrincipal")
    val fotoPrincipal: kotlin.String? = null,

    @SerializedName("porciones")
    val porciones: kotlin.Int? = null,

    @SerializedName("duracion")
    val duracion: kotlin.Int? = null,

    @SerializedName("cantidadPersonas")
    val cantidadPersonas: kotlin.Int? = null,

    @SerializedName("tipo")
    val tipo: TipoReceta? = null,

    @SerializedName("pasos")
    val pasos: kotlin.collections.List<Pasos>? = null,

    @SerializedName("utilizados")
    val utilizados: kotlin.collections.List<Utilizado>? = null,

    @SerializedName("fotos")
    val fotos: kotlin.collections.List<Foto>? = null,

    @SerializedName("calificaciones")
    val calificaciones: kotlin.collections.List<Calificacion>? = null,

    @SerializedName("fechaCreacion")
    val fechaCreacion: java.time.OffsetDateTime? = null,

    @SerializedName("habilitada")
    val habilitada: kotlin.Boolean? = null

) {


}

