/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idReceta 
 * @param nombre 
 * @param fotoPrincipal 
 * @param porciones 
 * @param promedioCalificacion 
 * @param tipo 
 * @param nombreUsuario 
 * @param fechaCreacion 
 * @param duracion 
 */


data class RecetaResumenResponse (

    @SerializedName("idReceta")
    val idReceta: kotlin.Long? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("fotoPrincipal")
    val fotoPrincipal: kotlin.String? = null,

    @SerializedName("porciones")
    val porciones: kotlin.Int? = null,

    @SerializedName("promedioCalificacion")
    val promedioCalificacion: kotlin.Double? = null,

    @SerializedName("tipo")
    val tipo: kotlin.String? = null,

    @SerializedName("nombreUsuario")
    val nombreUsuario: kotlin.String? = null,

    @SerializedName("fechaCreacion")
    val fechaCreacion: java.time.OffsetDateTime? = null,

    @SerializedName("duracion")
    val duracion: kotlin.Int? = null

) {


}

