/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nombre 
 * @param apellido 
 * @param alias 
 * @param email 
 * @param password 
 * @param role 
 */


data class RegisterRequest (

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("apellido")
    val apellido: kotlin.String? = null,

    @SerializedName("alias")
    val alias: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("password")
    val password: kotlin.String? = null,

    @SerializedName("role")
    val role: RegisterRequest.Role? = null

) {

    /**
     * 
     *
     * Values: VISITANTE,ALUMNO,USUARIO,ADMIN
     */
    enum class Role(val value: kotlin.String) {
        @SerializedName(value = "VISITANTE") VISITANTE("VISITANTE"),
        @SerializedName(value = "ALUMNO") ALUMNO("ALUMNO"),
        @SerializedName(value = "USUARIO") USUARIO("USUARIO"),
        @SerializedName(value = "ADMIN") ADMIN("ADMIN");
    }

}

