/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param email 
 * @param nuevaPassword 
 */


data class ResetPasswordDto (

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("nuevaPassword")
    val nuevaPassword: kotlin.String? = null

) {


}

