/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idSede 
 * @param nombreSede 
 * @param direccionSede 
 * @param telefonoSede 
 * @param mailSede 
 * @param whatsapp 
 * @param tipoBonificacion 
 * @param bonificaCursos 
 * @param tipoPromocion 
 * @param promocionCursos 
 */


data class Sede (

    @SerializedName("idSede")
    val idSede: kotlin.Long? = null,

    @SerializedName("nombreSede")
    val nombreSede: kotlin.String? = null,

    @SerializedName("direccionSede")
    val direccionSede: kotlin.String? = null,

    @SerializedName("telefonoSede")
    val telefonoSede: kotlin.String? = null,

    @SerializedName("mailSede")
    val mailSede: kotlin.String? = null,

    @SerializedName("whatsapp")
    val whatsapp: kotlin.String? = null,

    @SerializedName("tipoBonificacion")
    val tipoBonificacion: kotlin.String? = null,

    @SerializedName("bonificaCursos")
    val bonificaCursos: kotlin.Boolean? = null,

    @SerializedName("tipoPromocion")
    val tipoPromocion: kotlin.String? = null,

    @SerializedName("promocionCursos")
    val promocionCursos: kotlin.String? = null

) {


}

