/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idTipo 
 * @param descripcion 
 */


data class TipoReceta (

    @SerializedName("idTipo")
    val idTipo: kotlin.Long? = null,

    @SerializedName("descripcion")
    val descripcion: TipoReceta.Descripcion? = null

) {

    /**
     * 
     *
     * Values: POSTRE,SALADO,VEGETARIANO,ENSALADA,DESAYUNO,ALMUERZO,CENA,SNACKS,VEGANO,PASTAS
     */
    enum class Descripcion(val value: kotlin.String) {
        @SerializedName(value = "POSTRE") POSTRE("POSTRE"),
        @SerializedName(value = "SALADO") SALADO("SALADO"),
        @SerializedName(value = "VEGETARIANO") VEGETARIANO("VEGETARIANO"),
        @SerializedName(value = "ENSALADA") ENSALADA("ENSALADA"),
        @SerializedName(value = "DESAYUNO") DESAYUNO("DESAYUNO"),
        @SerializedName(value = "ALMUERZO") ALMUERZO("ALMUERZO"),
        @SerializedName(value = "CENA") CENA("CENA"),
        @SerializedName(value = "SNACKS") SNACKS("SNACKS"),
        @SerializedName(value = "VEGANO") VEGANO("VEGANO"),
        @SerializedName(value = "PASTAS") PASTAS("PASTAS");
    }

}

