/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idReceta 
 * @param nombreReceta 
 * @param fotoPrincipal 
 * @param promedioCalificacion 
 */


data class TopRecetaResponse (

    @SerializedName("idReceta")
    val idReceta: kotlin.Long? = null,

    @SerializedName("nombreReceta")
    val nombreReceta: kotlin.String? = null,

    @SerializedName("fotoPrincipal")
    val fotoPrincipal: kotlin.String? = null,

    @SerializedName("promedioCalificacion")
    val promedioCalificacion: kotlin.Double? = null

) {


}

