/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idUnidad 
 * @param descripcion 
 */


data class Unidad (

    @SerializedName("idUnidad")
    val idUnidad: kotlin.Long? = null,

    @SerializedName("descripcion")
    val descripcion: kotlin.String? = null

) {


}

