/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.GrantedAuthority

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param alias 
 * @param email 
 * @param password 
 * @param id 
 * @param nombre 
 * @param apellido 
 * @param rol 
 * @param habilitado 
 * @param codigoConfirmacion 
 * @param enabled 
 * @param authorities 
 * @param username 
 * @param credentialsNonExpired 
 * @param accountNonExpired 
 * @param accountNonLocked 
 */


data class Usuario (

    @SerializedName("alias")
    val alias: kotlin.String,

    @SerializedName("email")
    val email: kotlin.String,

    @SerializedName("password")
    val password: kotlin.String,

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("nombre")
    val nombre: kotlin.String? = null,

    @SerializedName("apellido")
    val apellido: kotlin.String? = null,

    @SerializedName("rol")
    val rol: Usuario.Rol? = null,

    @SerializedName("habilitado")
    val habilitado: kotlin.Boolean? = null,

    @SerializedName("codigoConfirmacion")
    val codigoConfirmacion: kotlin.String? = null,

    @SerializedName("enabled")
    val enabled: kotlin.Boolean? = null,

    @SerializedName("authorities")
    val authorities: kotlin.collections.List<GrantedAuthority>? = null,

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("credentialsNonExpired")
    val credentialsNonExpired: kotlin.Boolean? = null,

    @SerializedName("accountNonExpired")
    val accountNonExpired: kotlin.Boolean? = null,

    @SerializedName("accountNonLocked")
    val accountNonLocked: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: VISITANTE,ALUMNO,USUARIO,ADMIN
     */
    enum class Rol(val value: kotlin.String) {
        @SerializedName(value = "VISITANTE") VISITANTE("VISITANTE"),
        @SerializedName(value = "ALUMNO") ALUMNO("ALUMNO"),
        @SerializedName(value = "USUARIO") USUARIO("USUARIO"),
        @SerializedName(value = "ADMIN") ADMIN("ADMIN");
    }

}

