/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.saborchef.models

import com.example.saborchef.models.Ingrediente
import com.example.saborchef.models.Unidad

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idUtilizado 
 * @param ingrediente 
 * @param cantidad 
 * @param unidad 
 * @param observaciones 
 * @param receta 
 */


data class Utilizado (

    @SerializedName("idUtilizado")
    val idUtilizado: kotlin.Long? = null,

    @SerializedName("ingrediente")
    val ingrediente: Ingrediente? = null,

    @SerializedName("cantidad")
    val cantidad: kotlin.Double? = null,

    @SerializedName("unidad")
    val unidad: Unidad? = null,

    @SerializedName("observaciones")
    val observaciones: kotlin.String? = null,

    @SerializedName("receta")
    val receta: kotlin.Any? = null

) {


}

